DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMPT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    recordingURL TEXT NOT NULL,
    tags TEXT NOT NULL,
    summary TEXT NOT NULL,
    transcription TEXT NOT NULL
)